# Generated by Django 5.2.12 on 2026-03-14 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('CA', 'Cardio'), ('YO', 'Yoga'), ('ST', 'Strength')], max_length=3)),
                ('category_description', models.CharField(max_length=100)),
                ('is_highly_demanded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('biography', models.TextField()),
                ('experience_level', models.CharField(choices=[('BE', 'Beginner'), ('CE', 'Certified'), ('PT', 'Professional Trainer')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=30)),
                ('short_description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('price_per_training_session', models.IntegerField()),
                ('number_of_available_spots', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1app.category')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1app.instructor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
